test: action

diff --git a/.github/workflows/check_challenge_0.yml b/.github/workflows/check_challenge_0.yml
--- a/.github/workflows/check_challenge_0.yml
+++ b/.github/workflows/check_challenge_0.yml
@@ -17,13 +17,24 @@ jobs:
       run: |
         ls -R challenges
 
-    - name: Check Challenge-0 existence
+    - name: Check Challenge-0 completion
       run: |
         CHALLENGE_PATH="challenges/0-hello-world"
-        if [ -d "$CHALLENGE_PATH" ]; then
-          echo "Challenge-0 exists. Proceeding..."
-          # Add your logic here to check completion or perform further steps
-        else
-          echo "Challenge-0 does not exist. Skipping the workflow."
-          exit 78  # Exiting with a neutral exit code to indicate skipping
-        fi
+
+        # Iterate over language folders
+        for LANG_FOLDER in "$CHALLENGE_PATH"/*; do
+          if [ -d "$LANG_FOLDER" ]; then
+            GITHUB_USERNAME=$(basename "$(pwd)")
+            USER_PATH="$LANG_FOLDER/$GITHUB_USERNAME"
+
+            if [ -d "$USER_PATH" ]; then
+              echo "Challenge-0 completed by $GITHUB_USERNAME in $(basename "$LANG_FOLDER")."
+              # Add your logic here to perform further steps if needed
+              exit 0  # Exiting with a successful exit code
+            fi
+          fi
+        done
+
+        # If no matching user folder is found, exit with a non-successful code
+        echo "Challenge-0 not completed by $GITHUB_USERNAME in any language folder."
+        exit 1
